# Energy Consumption Forecasting via Recurrent Neural Network Architectures
### A Comparative Study of LSTM, GRU, BiLSTM, and BiGRU Models
>**Author:** Erdem YILMAZ  
**Institution:** Adana Alparslan Türkeş Science and Technology University  
**Department:** Artificial Intelligence Engineering  
**Date:** June 2026
**GitHub:** https://github.com/eerdemYlmzz
 **LinkedIn:** www.linkedin.com/in/erdem-yilmaz-24818727a

In [21]:
# import torch
# import torch.nn as nn
# import pandas as pd
# import numpy as np
# import math
# import random
# import time
# import matplotlib.pyplot as plt

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

# df=pd.read_csv("/content/drive/MyDrive/powerconsumption.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# df.head(20)

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964
5,1/1/2017 0:50,5.853,76.9,0.081,0.059,0.108,26624.81013,17416.41337,18130.12048
6,1/1/2017 1:00,5.641,77.7,0.080,0.048,0.096,25998.98734,16993.31307,17945.06024
7,1/1/2017 1:10,5.496,78.2,0.085,0.055,0.093,25446.07595,16661.39818,17459.27711
8,1/1/2017 1:20,5.678,78.1,0.081,0.066,0.141,24777.72152,16227.35562,17025.54217
9,1/1/2017 1:30,5.491,77.3,0.082,0.062,0.111,24279.49367,15939.20973,16794.21687
10,1/1/2017 1:40,5.516,77.5,0.081,0.051,0.108,23896.70886,15435.86626,16638.07229
11,1/1/2017 1:50,5.471,76.7,0.083,0.059,0.126,23544.30380,15213.37386,16395.18072
12,1/1/2017 2:00,5.059,78.6,0.081,0.070,0.096,23003.54430,15169.60486,16117.59036
13,1/1/2017 2:10,4.968,78.8,0.084,0.070,0.134,22329.11392,14710.03040,15822.65060
14,1/1/2017 2:20,4.975,78.9,0.083,0.055,0.152,22092.15190,14421.88450,15672.28916
15,1/1/2017 2:30,4.897,79.1,0.083,0.070,0.096,21903.79747,14104.55927,15597.10843
16,1/1/2017 2:40,5.020,79.7,0.081,0.051,0.134,21685.06329,13965.95745,15510.36145
17,1/1/2017 2:50,5.407,78.5,0.082,0.062,0.163,21484.55696,13612.15805,15336.86747
18,1/1/2017 3:00,5.169,77.9,0.083,0.066,0.108,21107.84810,13535.56231,15140.24096
19,1/1/2017 3:10,5.081,77.7,0.084,0.051,0.130,20998.48101,13371.42857,15059.27711

In [ ]:
# df.rename(columns={"Datetime":"time","PowerConsumption_Zone1":"consumption"},inplace=True)

In [ ]:
# df=df.drop(columns=["Temperature",	"Humidity",	"WindSpeed",	"GeneralDiffuseFlows",	"DiffuseFlows","PowerConsumption_Zone2",	"PowerConsumption_Zone3"])

In [ ]:
# df.head()

            time  consumption
0  1/1/2017 0:00  34055.69620
1  1/1/2017 0:10  29814.68354
2  1/1/2017 0:20  29128.10127
3  1/1/2017 0:30  28228.86076
4  1/1/2017 0:40  27335.69620

In [ ]:
# device ="cuda" if torch.cuda.is_available() else "cpu"
# device

'cuda'

In [ ]:
# x,y=df.shape
# x

52416

In [ ]:
# df["time"]=df["time"].apply(lambda x:pd.to_datetime(x).strftime("%H:%M"))

# df.to_parquet("/content/drive/MyDrive/processed_powerconsumption.parquet", index=False)

**Mounted data. **EXECUTE** the cells from this point**








---

In [23]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import math
import random
import time
import matplotlib.pyplot as plt

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
import pandas as pd

df = pd.read_parquet("/content/drive/MyDrive/processed_powerconsumption.parquet")

print(df.head())

    time  consumption
0  00:00    34.055696
1  00:10    29.814684
2  00:20    29.128101
3  00:30    28.228861
4  00:40    27.335696

In [26]:
df["consumption"]=df["consumption"] /1000

In [27]:
df["consumption"]

0        0.034056
1        0.029815
2        0.029128
3        0.028229
4        0.027336
           ...
52411    0.031160
52412    0.030430
52413    0.029591
52414    0.028958
52415    0.028350
Name: consumption, Length: 52416, dtype: float64

In [28]:
df

        time  consumption
0      00:00     0.034056
1      00:10     0.029815
2      00:20     0.029128
3      00:30     0.028229
4      00:40     0.027336
...      ...          ...
52411  23:10     0.031160
52412  23:20     0.030430
52413  23:30     0.029591
52414  23:40     0.028958
52415  23:50     0.028350

[52416 rows x 2 columns]

In [29]:
# plt.plot(df["time"],df["consumption"])

In [30]:
#plt.bar(df["time"],df["consumption"],color="skyblue")

In [31]:
len(df)

52416

In [32]:
x,y=df.shape

x / 144

day=[]
for i in range(0,len(df),144):
  each_day=df.iloc[i:i+144]
  day.append(each_day)

##**Annual electricity consumption records**.

In [33]:
day_list = [pd.DataFrame(i, columns=['time', 'consumption']) for i in day]
df_day = pd.concat(day_list, ignore_index=True)

In [34]:
df_day

        time  consumption
0      00:00     0.034056
1      00:10     0.029815
2      00:20     0.029128
3      00:30     0.028229
4      00:40     0.027336
...      ...          ...
52411  23:10     0.031160
52412  23:20     0.030430
52413  23:30     0.029591
52414  23:40     0.028958
52415  23:50     0.028350

[52416 rows x 2 columns]

In [35]:
type(df_day) # means day 3

pandas.core.frame.DataFrame

In [36]:
df_day.index

RangeIndex(start=0, stop=52416, step=1)

In [37]:
n=144
daily_sum=df_day["consumption"].groupby(df_day.index//n).sum()
daily_sum
df_daily_sum=pd.DataFrame({
    'day': [f'Day {i+1}' for i in range(len(daily_sum))],
    'total_consumption': daily_sum.values
})
df_daily_sum

         day  total_consumption
0      Day 1           4.098993
1      Day 2           4.157207
2      Day 3           4.400992
3      Day 4           4.419336
4      Day 5           4.435619
..       ...                ...
359  Day 360           4.321941
360  Day 361           4.315243
361  Day 362           4.358449
362  Day 363           4.206187
363  Day 364           4.052976

[364 rows x 2 columns]

In [38]:
daily=df_daily_sum

In [39]:
daily

         day  total_consumption
0      Day 1           4.098993
1      Day 2           4.157207
2      Day 3           4.400992
3      Day 4           4.419336
4      Day 5           4.435619
..       ...                ...
359  Day 360           4.321941
360  Day 361           4.315243
361  Day 362           4.358449
362  Day 363           4.206187
363  Day 364           4.052976

[364 rows x 2 columns]

In [40]:
from sklearn.preprocessing import MinMaxScaler

# Correctly select the 'total_consumption'  column for scaling
consumption_values = daily['total_consumption'].values.reshape(-1, 1)

scaler=MinMaxScaler(feature_range=(-1,1))
scaled_data=scaler.fit_transform(consumption_values)
scaled_data

array([[-7.16817201e-01],
       [-6.49226100e-01],
       [-3.66170286e-01],
       [-3.44872140e-01],
       [-3.25965539e-01],
       [-3.41126094e-01],
       [-3.57768136e-01],
       [-5.33790009e-01],
       [-3.69881060e-01],
       [-1.48673819e-01],
       [-2.83355138e-01],
       [-1.13118120e-01],
       [-2.13414821e-01],
       [-3.20653348e-01],
       [-1.00000000e+00],
       [-3.62022121e-01],
       [-1.53964846e-01],
       [ 1.80570111e-02],
       [-1.02373809e-01],
       [-1.62070698e-01],
       [-1.37851906e-01],
       [-3.06106552e-01],
       [-4.13153621e-02],
       [-1.95495877e-01],
       [-7.50438929e-02],
       [-9.67502286e-03],
       [-7.62008642e-02],
       [-2.43150390e-01],
       [-5.83836066e-01],
       [-2.05400679e-01],
       [-1.93703983e-01],
       [-2.30448967e-01],
       [-1.45724296e-01],
       [-3.37150051e-01],
       [-3.48754618e-01],
       [-7.51124188e-01],
       [-3.69817119e-01],
       [-3.41188271e-01],
       [-3.53784680e-01],
       [-3.40826956e-01],
       [-3.41670023e-01],
       [-2.84206873e-01],
       [-4.63964301e-01],
       [-6.72128148e-02],
       [-5.14073641e-01],
       [-3.06544601e-01],
       [-2.33162367e-01],
       [-1.84122801e-01],
       [-2.20721818e-01],
       [-4.51672529e-01],
       [-1.02366575e-01],
       [-1.36847299e-01],
       [-1.62089710e-01],
       [-2.37559094e-02],
       [-2.49549035e-01],
       [-3.54245179e-01],
       [-4.58870477e-01],
       [-2.34140041e-01],
       [-2.63023935e-01],
       [-2.68787328e-01],
       [-2.94364826e-01],
       [-2.79644425e-01],
       [-2.93326074e-01],
       [-5.40613167e-01],
       [-1.27367598e-01],
       [-2.72216634e-01],
       [-1.94796480e-02],
       [-2.61622783e-01],
       [-3.04396612e-01],
       [-3.03130188e-01],
       [-5.49897905e-01],
       [-2.12616439e-01],
       [-2.79921899e-01],
       [-4.55907516e-02],
       [-2.54418018e-02],
       [-2.19048166e-01],
       [-2.75638825e-01],
       [-4.88398074e-01],
       [-2.70658505e-01],
       [-3.38134720e-01],
       [-2.21709079e-01],
       [-2.62533470e-01],
       [-3.67177097e-01],
       [-4.14931247e-01],
       [-5.37390189e-01],
       [-1.74339126e-01],
       [-3.20177111e-01],
       [ 4.89072537e-02],
       [-1.17221976e-01],
       [-2.42299143e-01],
       [-5.54968928e-02],
       [-6.25239012e-01],
       [-1.79909762e-01],
       [-1.95329989e-01],
       [-1.82659775e-01],
       [-1.40200158e-01],
       [-1.93076707e-01],
       [-2.48508896e-01],
       [-5.07636383e-01],
       [-2.52741899e-01],
       [-2.07525071e-01],
       [-2.03371256e-01],
       [-1.92018456e-01],
       [-2.45521317e-01],
       [-2.83517563e-01],
       [-5.87386746e-01],
       [-1.10453949e-01],
       [-1.00274583e-01],
       [-9.39106801e-02],
       [-7.22166154e-01],
       [-3.70746886e-02],
       [-2.21491103e-01],
       [-5.63169358e-01],
       [-2.19101040e-01],
       [-1.54029409e-01],
       [-1.61019624e-01],
       [-1.81205580e-01],
       [-2.01017188e-01],
       [-2.27783016e-01],
       [-6.46015284e-01],
       [-5.66133436e-01],
       [-1.36794904e-01],
       [-3.67471173e-01],
       [-1.08143098e-01],
       [-1.60549589e-01],
       [-1.61353594e-01],
       [-5.43942905e-01],
       [-4.23901285e-02],
       [-9.57468070e-02],
       [ 1.48988640e-02],
       [ 3.24450766e-04],
       [-6.46683689e-02],
       [-1.27833905e-01],
       [-4.38048171e-01],
       [-2.09451293e-02],
       [-8.73887546e-03],
       [-1.69104873e-02],
       [-5.52285653e-03],
       [-1.01140948e-01],
       [-1.10686677e-01],
       [-2.08234379e-01],
       [ 8.96859233e-02],
       [ 1.24550493e-01],
       [ 6.97319874e-02],
       [ 1.43525004e-01],
       [ 1.87759884e-01],
       [ 2.03152920e-01],
       [-3.54172147e-02],
       [ 2.36000168e-01],
       [ 1.96384662e-01],
       [ 2.06895196e-01],
       [ 2.67187323e-01],
       [ 3.60049629e-01],
       [ 5.38850167e-01],
       [-8.65752475e-02],
       [ 2.83825768e-01],
       [ 2.55406064e-01],
       [ 2.64175573e-01],
       [ 3.56565447e-01],
       [ 3.59326218e-01],
       [ 4.68369301e-01],
       [ 5.74572891e-02],
       [ 4.63748331e-01],
       [ 4.26042396e-01],
       [ 3.93651315e-01],
       [ 4.64885119e-01],
       [ 4.41042095e-01],
       [ 4.31947789e-01],
       [ 1.87656442e-01],
       [ 5.94626604e-01],
       [ 7.15480473e-01],
       [ 7.65587733e-01],
       [ 6.49842029e-01],
       [ 6.98856792e-01],
       [ 6.50860710e-01],
       [ 4.51287952e-01],
       [-2.44249242e-01],
       [-6.10073578e-01],
       [-1.12027491e-01],
       [-1.01058224e-01],
       [-9.81276725e-02],
       [-8.82594126e-02],
       [-1.92058222e-01],
       [ 1.87335128e-01],
       [ 5.54369482e-02],
       [ 4.39155557e-01],
       [ 5.50486538e-01],
       [ 1.80380645e-01],
       [ 3.19411059e-01],
       [-3.53046152e-02],
       [ 5.18684035e-01],
       [ 6.29007764e-01],
       [ 6.97923063e-01],
       [ 6.71534539e-01],
       [ 2.93570599e-01],
       [ 4.64240578e-01],
       [ 3.69477412e-01],
       [ 6.89598421e-01],
       [ 7.50544578e-01],
       [ 8.51610475e-01],
       [ 6.64476368e-01],
       [ 4.57360157e-01],
       [ 4.20832456e-01],
       [ 1.61813138e-01],
       [ 8.84605388e-01],
       [ 9.52587498e-01],
       [ 9.05720650e-01],
       [ 9.31294485e-01],
       [ 8.62786530e-01],
       [ 8.77502779e-01],
       [ 5.11862864e-01],
       [ 9.75354357e-01],
       [ 8.23436105e-01],
       [ 7.42706760e-01],
       [ 7.46989661e-01],
       [ 7.65420239e-01],
       [ 8.03253769e-01],
       [ 3.91427224e-01],
       [ 9.04566276e-01],
       [ 1.00000000e+00],
       [ 7.33977659e-01],
       [ 6.91252566e-01],
       [ 6.62838449e-01],
       [ 5.65845957e-01],
       [ 3.81755439e-01],
       [ 5.20626835e-01],
       [ 7.55362473e-01],
       [ 7.83850817e-01],
       [ 8.73042046e-01],
       [ 7.63134046e-01],
       [ 7.31721156e-01],
       [ 3.39921071e-01],
       [ 5.48068577e-01],
       [ 6.35218562e-01],
       [ 6.53671408e-01],
       [ 6.57620287e-01],
       [ 5.60390268e-01],
       [ 5.77558986e-01],
       [ 4.01507258e-01],
       [ 5.69965558e-01],
       [ 4.16961331e-01],
       [ 3.37715834e-02],
       [ 5.18087576e-02],
       [-5.43156656e-01],
       [-3.02208829e-01],
       [-2.06640527e-01],
       [-1.42839549e-01],
       [ 1.08458181e-01],
       [-5.29825594e-02],
       [ 2.95096756e-01],
       [ 2.62352887e-01],
       [ 1.56752799e-01],
       [-1.44178600e-01],
       [ 1.86552235e-01],
       [ 3.57625266e-01],
       [ 4.40158164e-01],
       [ 4.69343560e-01],
       [ 2.49709581e-01],
       [ 1.33448870e-01],
       [-1.44319164e-01],
       [ 1.17609597e-01],
       [ 2.10078106e-01],
       [ 2.12778403e-01],
       [ 1.55761457e-01],
       [ 9.21454307e-02],
       [ 1.84880271e-01],
       [-8.89076002e-02],
       [ 3.00578728e-01],
       [ 1.29587076e-01],
       [ 4.13968987e-01],
       [ 3.26605147e-01],
       [ 2.67346586e-01],
       [-2.14497281e-01],
       [-6.89697944e-02],
       [ 2.14093414e-01],
       [ 2.76603663e-01],
       [ 2.17810516e-01],
       [ 1.29119573e-01],
       [ 1.27400047e-01],
       [ 1.99268907e-01],
       [-1.94986725e-02],
       [ 1.72963821e-01],
       [ 1.25095151e-01],
       [ 2.50276626e-01],
       [ 3.16452758e-01],
       [ 2.16259285e-01],
       [ 2.21900793e-01],
       [ 5.51859800e-03],
       [ 2.49069300e-01],
       [ 3.03911196e-01],
       [ 1.76600435e-01],
       [ 1.33392777e-01],
       [ 3.69164066e-02],
       [ 5.22677473e-02],
       [-1.44906979e-01],
       [ 8.24435951e-02],
       [ 1.39444045e-01],
       [-1.69726687e-01],
       [-3.59459891e-01],
       [-5.10829377e-01],
       [-4.90517022e-01],
       [-6.99267449e-01],
       [-4.18165232e-01],
       [-3.75945386e-01],
       [-4.53528753e-01],
       [-5.23536904e-01],
       [-5.79383373e-01],
       [-5.94581101e-01],
       [-8.80401273e-01],
       [-7.09117808e-01],
       [-5.78125827e-01],
       [-6.29420838e-01],
       [-6.04312791e-01],
       [-6.61331065e-01],
       [-7.59176708e-01],
       [-9.27244857e-01],
       [-6.00818814e-01],
       [-6.15780752e-01],
       [-5.01758496e-01],
       [-4.49334552e-01],
       [-6.77264742e-01],
       [-7.32539600e-01],
       [-9.02458342e-01],
       [-6.23976236e-01],
       [-5.62728035e-01],
       [-5.83856235e-01],
       [-5.82148545e-01],
       [-6.65911104e-01],
       [-6.65510976e-01],
       [-7.44772092e-01],
       [-6.27327310e-01],
       [-4.97728633e-01],
       [-3.84842455e-01],
       [-4.92691304e-01],
       [-9.62483961e-01],
       [-8.49882421e-01],
       [-9.59022776e-01],
       [-6.02054490e-01],
       [-5.61382031e-01],
       [-5.74160162e-01],
       [-6.02619582e-01],
       [-6.35416078e-01],
       [-5.86775829e-01],
       [-8.16379560e-01],
       [-4.48505009e-01],
       [-5.30838837e-01],
       [-5.29729845e-01],
       [-5.06737685e-01],
       [-5.62003632e-01],
       [-6.67110646e-01],
       [-9.26254534e-01],
       [-5.23464393e-01],
       [-5.17855860e-01],
       [-5.04272474e-01],
       [-5.21818564e-01],
       [-6.31022492e-01],
       [-6.32237439e-01],
       [-8.83667828e-01],
       [-4.63395169e-01],
       [-4.57956163e-01],
       [-4.65733235e-01],
       [-4.15567239e-01],
       [-5.92356108e-01],
       [-7.70246905e-01]])

In [41]:
def create_dataset(scaled_data, lookback=7):
    X, y = [], []
    for i in range(len(scaled_data) - lookback):
        X.append(scaled_data[i:(i + lookback), 0])
        y.append(scaled_data[i + lookback, 0])
    return np.array(X), np.array(y)

In [42]:
lookback=7
X,y=create_dataset(scaled_data,lookback)

In [43]:
y.shape

(357,)

In [44]:
X = X.reshape(X.shape[0], X.shape[1], 1)
y=y.reshape(y.shape[0],1)

In [45]:
split_index= int(len(X)*0.95)
split_index

339

In [46]:
X_train=X[:split_index]
X_test=X[split_index:]
y_test=y[split_index:]
y_train=y[:split_index]

In [47]:
print(X_train.shape)
print(type(X))

(339, 7, 1)
<class 'numpy.ndarray'>

In [48]:
X_train=torch.tensor(X_train).float()
y_train=torch.tensor(y_train).float()
X_test=torch.tensor(X_test).float()
y_test=torch.tensor(y_test).float()
y_test.shape
X_test.shape

torch.Size([18, 7, 1])

In [49]:
from torch.utils.data import Dataset
class TimeSeriesDataset(Dataset):
  def __init__(self,X,y):
    self.X=X
    self.y=y

  def __len__(self):
    return len(self.X)
  def __getitem__(self,i):
    return self.X[i],self.y[i]

train_data=TimeSeriesDataset(X_train,y_train)
test_data=TimeSeriesDataset(X_test,y_test)

In [50]:
from torch.utils.data import DataLoader
batch_size=16
train_loader=DataLoader(train_data,batch_size=batch_size,shuffle=True)
test_loader=DataLoader(test_data,batch_size=batch_size,shuffle=False)

In [51]:
class LSTMForecaster(nn.Module):
  def __init__(self):
    super().__init__()
    self.lstm=nn.LSTM(input_size=1,hidden_size=32,num_layers=1,bias=True,batch_first=True)
    self.linear=nn.Linear(in_features=32,out_features=1)
    self.dropout=nn.Dropout(p=0.5)

  def forward(self,x):
    x,_= self.lstm(x)
    x = x[:, -1, :]
    x=self.dropout(x)
    x=self.linear(x)
    return x

In [52]:
import torch.optim as optim
import torch.utils.data as data

In [53]:
model=LSTMForecaster()
optimizer=optim.Adam(model.parameters(),lr=0.01)
loss_f = nn.MSELoss()

In [54]:

n_epochs=6000

for epoch in range(n_epochs):
  model.train()

  for X_batch,y_batch in train_loader:
    y_pred=model(X_batch)
    loss = loss_f(y_pred.squeeze(1), y_batch.squeeze(1))
    optimizer.zero_grad()
    loss.backward()
    gradient_clipping=nn.utils.clip_grad_norm_(model.parameters(),max_norm=1.0)
    optimizer.step()

  if epoch % 100 !=0:
    continue
  model.eval()
  with torch.no_grad():
    y_pred_t=model(X_train)
    train_rmse = np.sqrt(loss_f(y_pred_t.squeeze(1), y_train.squeeze(1)).item())
    y_pred_test=model(X_test)
    test_rmse = np.sqrt(loss_f(y_pred_test.squeeze(1), y_test.squeeze(1)).item())
  print("Epoch %d: train RMSE %.4f,test RMSE %.4f" % (epoch,train_rmse,test_rmse))

Epoch 0: train RMSE 0.2498,test RMSE 0.1807
Epoch 100: train RMSE 0.1996,test RMSE 0.2026
Epoch 200: train RMSE 0.1693,test RMSE 0.1112
Epoch 300: train RMSE 0.1490,test RMSE 0.1248
Epoch 400: train RMSE 0.1352,test RMSE 0.0909
Epoch 500: train RMSE 0.0994,test RMSE 0.0905
Epoch 600: train RMSE 0.0919,test RMSE 0.0915
Epoch 700: train RMSE 0.0767,test RMSE 0.1071
Epoch 800: train RMSE 0.0882,test RMSE 0.1081
Epoch 900: train RMSE 0.0747,test RMSE 0.0711
Epoch 1000: train RMSE 0.0734,test RMSE 0.0800
Epoch 1100: train RMSE 0.0605,test RMSE 0.1148
Epoch 1200: train RMSE 0.0650,test RMSE 0.0689
Epoch 1300: train RMSE 0.0642,test RMSE 0.0900
Epoch 1400: train RMSE 0.0588,test RMSE 0.0781
Epoch 1500: train RMSE 0.0613,test RMSE 0.0756
Epoch 1600: train RMSE 0.0533,test RMSE 0.1004
Epoch 1700: train RMSE 0.0443,test RMSE 0.0836
Epoch 1800: train RMSE 0.0621,test RMSE 0.0803
Epoch 1900: train RMSE 0.0474,test RMSE 0.1136
Epoch 2000: train RMSE 0.0431,test RMSE 0.0905
Epoch 2100: train RMSE 0.0654,test RMSE 0.0938
Epoch 2200: train RMSE 0.0535,test RMSE 0.1071
Epoch 2300: train RMSE 0.0552,test RMSE 0.1011
Epoch 2400: train RMSE 0.0646,test RMSE 0.0760
Epoch 2500: train RMSE 0.0528,test RMSE 0.0990
Epoch 2600: train RMSE 0.0468,test RMSE 0.0881
Epoch 2700: train RMSE 0.0520,test RMSE 0.0817
Epoch 2800: train RMSE 0.0492,test RMSE 0.1194
Epoch 2900: train RMSE 0.0437,test RMSE 0.0847
Epoch 3000: train RMSE 0.0522,test RMSE 0.0863
Epoch 3100: train RMSE 0.0483,test RMSE 0.0713
Epoch 3200: train RMSE 0.0460,test RMSE 0.0943
Epoch 3300: train RMSE 0.0454,test RMSE 0.0716
Epoch 3400: train RMSE 0.0738,test RMSE 0.1196
Epoch 3500: train RMSE 0.0323,test RMSE 0.0885
Epoch 3600: train RMSE 0.0382,test RMSE 0.1087
Epoch 3700: train RMSE 0.0311,test RMSE 0.1039
Epoch 3800: train RMSE 0.0384,test RMSE 0.0990
Epoch 3900: train RMSE 0.0454,test RMSE 0.0885
Epoch 4000: train RMSE 0.0433,test RMSE 0.0757
Epoch 4100: train RMSE 0.0371,test RMSE 0.0940
Epoch 4200: train RMSE 0.0530,test RMSE 0.0879
Epoch 4300: train RMSE 0.0321,test RMSE 0.0950
Epoch 4400: train RMSE 0.0387,test RMSE 0.0918
Epoch 4500: train RMSE 0.0398,test RMSE 0.0707
Epoch 4600: train RMSE 0.0388,test RMSE 0.1101
Epoch 4700: train RMSE 0.0372,test RMSE 0.0817
Epoch 4800: train RMSE 0.0356,test RMSE 0.0958
Epoch 4900: train RMSE 0.0446,test RMSE 0.0989
Epoch 5000: train RMSE 0.0459,test RMSE 0.1022
Epoch 5100: train RMSE 0.0445,test RMSE 0.0907
Epoch 5200: train RMSE 0.0372,test RMSE 0.0850

KeyboardInterrupt:


try with higher num_layer and  more than 1 LSTM layer.